'use client'

import { useEffect, useMemo, useRef, useState } from 'react'
import { Button, Modal, Select, Tooltip, message } from 'antd'
import { CloseOutlined, InfoCircleOutlined } from '@ant-design/icons'
import { assetUrl } from '~/utils/assetUrl'
import dialogSelectNorIconRaw from '~/assets/img/icon/dialog-select-nor.svg'
import dialogSelectSelIconRaw from '~/assets/img/icon/dialog-select-sel.svg'
import starWhiteIconRaw from '~/assets/img/icon/star_white.svg'
import { emptyImageIconUrl as emptyImageIconRaw } from '~/utils/emptyImageIcon'
import { ShimmerImage } from '~/components/common/ShimmerImage'
import { ShimmerVideo } from '~/components/common/ShimmerVideo'
import { BillingQuoteHint } from '~/components/common/BillingQuoteHint'
import { billingQuoteTextForDisplay } from '~/utils/billingQuoteDisplay'
import { useBillingQuote } from '~/hooks/useBillingQuote'
import ModelSelectDropdown from './ModelSelectDropdown'
import { resolveStoryboardPanelCoverImage } from '~/utils/storyboardImageCover'
import {
  isAutoGeneratedStoryboardPanel,
  manualStoryboardTooltip
} from '~/utils/storyboardManual'
import { parseServerStoryboardId } from '~/composables/useStoryboardWorkbenchMutations'
import { useCreationStore } from '~/stores/creation'
import { skipsStoryboardImageGeneration } from '~/utils/creationModeUiRules'
import { useRouteLike } from '~/composables/useRouteLike'
import type { StoryboardPanel, StoryboardVideoPanel } from '~/types'
import { refreshStoryboardPanelsFromApiForBatchModal } from '~/utils/batchModalListRefresh'
import { useBatchStoryboardModels } from './batch-generate-storyboard/useBatchStoryboardModels'
import {
  STORYBOARD_GEN_CONFIG_SCENE_CODES,
  getProjectGenConfigBySceneCode
} from '~/utils/projectGenConfig'
import { formatVideoResolutionForApi } from '~/utils/storyboardVideoGenerateParams'
import './BatchGenerateStoryboardModal.css'

const dialogSelectNorIcon = assetUrl(dialogSelectNorIconRaw)
const dialogSelectSelIcon = assetUrl(dialogSelectSelIconRaw)
const starWhiteIconUrl = assetUrl(starWhiteIconRaw)
const emptyImageIconUrl = assetUrl(emptyImageIconRaw)

interface Props {
  open: boolean
  mode: 'image' | 'video'
  /** generate 保持既有生图/生视频逻辑；delete 仅复用卡片选择能力。 */
  action?: 'generate' | 'delete'
  panels?: StoryboardPanel[]
  videoPanels?: StoryboardVideoPanel[]
  title?: string
  /** 打开时是否默认全选可选项 */
  preselectAll?: boolean
  onOpenChange: (value: boolean) => void
  onConfirm?: (payload: {
    action: 'generate' | 'delete'
    mode: 'image' | 'video'
    selectedStoryboardIds: number[]
    agent?: string
    model?: string
    videoModel?: string
    aspectRatio?: string
    resolution?: string
    durationSeconds?: number
    /** 音画同出偏好；模型不支持时固定为 none */
    soundEffects?: 'none' | 'with-sound'
  }) => void | Promise<void>
}

interface CardListItem {
  panel: StoryboardPanel
  panelIndex: number
  cover: string
  coverKind: 'image' | 'video'
  label: string
  canSelect: boolean
  disabledTooltip: string
}

/** 原 computed cardList：打开态刷新列表 / props 列表二选一推导 */
function computeCardList(
  mode: 'image' | 'video',
  action: 'generate' | 'delete',
  panels: StoryboardPanel[],
  videoPanels: StoryboardVideoPanel[],
  projectCreationMode: string
): CardListItem[] {
  const creationStore = useCreationStore.getState()
  return panels.map((panel, index) => {
    const storyboardImageUrl = String(resolveStoryboardPanelCoverImage(panel)?.url ?? '').trim()
    const hasStoryboardImage = !!storyboardImageUrl
    const isAutoPanel = isAutoGeneratedStoryboardPanel(panel, creationStore)
    const videoPanel = videoPanels[index]
    const videoCover = String(
      videoPanel?.videos?.find((v) => v.isStoryboardVideo && String(v.url ?? '').trim())?.url ?? ''
    ).trim()
    const displayCover =
      mode === 'video'
        ? action === 'delete'
          ? videoCover || storyboardImageUrl
          : storyboardImageUrl || videoCover
        : storyboardImageUrl
    const coverKind =
      mode === 'video' && videoCover && (action === 'delete' || !hasStoryboardImage)
        ? ('video' as const)
        : ('image' as const)

    let canSelect = action === 'delete' ? parseServerStoryboardId(panel.id) != null : isAutoPanel
    let disabledTooltip = ''
    if (action === 'delete') {
      if (!canSelect) disabledTooltip = '该分镜尚未保存到服务器，无法批量删除'
    } else {
      if (mode === 'video') {
        if (!isAutoPanel) {
          canSelect = false
          disabledTooltip = manualStoryboardTooltip('video')
        } else if (!hasStoryboardImage && !skipsStoryboardImageGeneration(projectCreationMode)) {
          // 专业版 / 多参数不出分镜图，批量出片不要求分镜图
          canSelect = false
          disabledTooltip = '需要先生成当前分镜视频对应的分镜图'
        }
      } else if (!isAutoPanel) {
        canSelect = false
        disabledTooltip = manualStoryboardTooltip('image')
      }
    }

    return {
      panel,
      panelIndex: index,
      cover: displayCover,
      coverKind,
      label: panel.title || `分镜${index + 1}`,
      canSelect,
      disabledTooltip
    }
  })
}

export function BatchGenerateStoryboardModal({
  open,
  mode,
  action = 'generate',
  panels = [],
  videoPanels = [],
  title = '',
  preselectAll = false,
  onOpenChange,
  onConfirm
}: Props) {
  const route = useRouteLike()
  const routeRef = useRef(route)
  routeRef.current = route

  // 订阅手动分镜 id 列表：变化时刷新 canSelect 推导
  useCreationStore((s) => s.manualStoryboardIds)
  const projectCreationMode = useCreationStore(
    (s) => s.formData.globalSetting?.creationMode || 'i2v'
  )
  const currentProjectId = useCreationStore((state) => state.currentProjectId)
  const currentEpisodeId = useCreationStore((state) => state.currentEpisodeId)

  const modalOpenInitGenRef = useRef(0)
  const [listLoading, setListLoading] = useState(false)
  const [confirmLoading, setConfirmLoading] = useState(false)
  const confirmLoadingRef = useRef(false)
  const listLoadingRef = useRef(false)
  const [refreshedPanels, setRefreshedPanelsState] = useState<StoryboardPanel[] | null>(null)
  const refreshedPanelsRef = useRef<StoryboardPanel[] | null>(null)
  const [refreshedVideoPanels, setRefreshedVideoPanelsState] = useState<
    StoryboardVideoPanel[] | null
  >(null)
  const refreshedVideoPanelsRef = useRef<StoryboardVideoPanel[] | null>(null)

  const setListLoadingBoth = (v: boolean) => {
    listLoadingRef.current = v
    setListLoading(v)
  }
  const setRefreshedPanels = (v: StoryboardPanel[] | null) => {
    refreshedPanelsRef.current = v
    setRefreshedPanelsState(v)
  }
  const setRefreshedVideoPanels = (v: StoryboardVideoPanel[] | null) => {
    refreshedVideoPanelsRef.current = v
    setRefreshedVideoPanelsState(v)
  }

  const [selectedIds, setSelectedIdsState] = useState<Set<string>>(new Set())
  const selectedIdsRef = useRef<Set<string>>(new Set())
  const setSelectedIds = (v: Set<string>) => {
    selectedIdsRef.current = v
    setSelectedIdsState(v)
  }

  /** 异步流程（打开初始化）内读最新 props */
  const propsSnapshotRef = useRef({ open, mode, action, panels, videoPanels, preselectAll })
  propsSnapshotRef.current = { open, mode, action, panels, videoPanels, preselectAll }

  const models = useBatchStoryboardModels({ projectCreationMode, routeRef })
  const {
    agent,
    model,
    loadImageAgents,
    initImageModelSelection,
    videoModel,
    videoAspectRatio,
    projectAspectRatio,
    videoModelOptions,
    videoModelsLoading,
    videoModelDropdownExpanded,
    setVideoModelDropdownExpanded,
    videoQuality,
    setVideoQuality,
    videoAudio,
    setVideoAudio,
    videoQualityOptions,
    videoAudioOptions,
    videoConfigShowAudio,
    selectedVideoModel,
    handleSelectVideoModel,
    initVideoModelSelection,
    invalidateVideoModelLoad
  } = models

  const [imageBillingConfig, setImageBillingConfig] = useState({
    ready: false,
    aspectRatio: '',
    resolution: ''
  })
  useEffect(() => {
    let cancelled = false
    setImageBillingConfig({ ready: false, aspectRatio: '', resolution: '' })
    if (!open || action !== 'generate' || mode !== 'image') return
    const projectId = Number(currentProjectId)
    if (!Number.isFinite(projectId) || projectId <= 0) return
    void getProjectGenConfigBySceneCode(projectId, STORYBOARD_GEN_CONFIG_SCENE_CODES.image)
      .then((config) => {
        if (cancelled) return
        setImageBillingConfig({
          ready: true,
          aspectRatio: String(config?.aspectRatio || '').trim(),
          resolution: String(config?.resolution || '').trim()
        })
      })
      .catch(() => {
        if (!cancelled) {
          setImageBillingConfig({ ready: true, aspectRatio: '', resolution: '' })
        }
      })
    return () => {
      cancelled = true
    }
  }, [action, currentProjectId, mode, open])

  const modalTitle = title
    ? title
    : action === 'delete'
      ? mode === 'image'
        ? '批量删除分镜图'
        : '批量删除分镜视频'
      : mode === 'image'
        ? '批量生成分镜图'
        : '批量生成分镜视频'

  const modalSubtitle =
    action === 'delete'
      ? '请选择需要删除的分镜，删除后将同步移除对应的分镜脚本、视频和配音'
      : mode === 'image'
        ? '生成结果将更新到分镜图，历史记录可在生图历史中查看'
        : ''

  const effectivePanels = refreshedPanels ?? panels
  const effectiveVideoPanels = refreshedVideoPanels ?? videoPanels

  const cardList = computeCardList(
    mode,
    action,
    effectivePanels,
    effectiveVideoPanels,
    projectCreationMode
  )

  /** 异步初始化（resetSelectionOnOpen）用：从 ref 快照推导当前列表 */
  function computeCardListLive(): CardListItem[] {
    const snap = propsSnapshotRef.current
    return computeCardList(
      snap.mode,
      snap.action,
      refreshedPanelsRef.current ?? snap.panels,
      refreshedVideoPanelsRef.current ?? snap.videoPanels,
      useCreationStore.getState().formData.globalSetting?.creationMode || 'i2v'
    )
  }

  const selectableCount = cardList.filter((c) => c.canSelect).length

  const withImageCount = cardList.filter((c) => !!c.cover).length

  const pendingCount = cardList.filter((c) => {
    if (!c.canSelect) return false
    const vp = effectiveVideoPanels[c.panelIndex]
    const hasVideo = (vp?.videos || []).some(
      (v) => v.isStoryboardVideo && String(v.url ?? '').trim()
    )
    return !hasVideo
  }).length

  const isAllSelectableChecked = (() => {
    const selectable = cardList.filter((c) => c.canSelect)
    if (selectable.length === 0) return false
    return selectable.every((c) => selectedIds.has(c.panel.id))
  })()

  const selectedStoryboardIds = useMemo(
    () =>
      [...selectedIds]
        .map((id) => parseServerStoryboardId(id))
        .filter((id): id is number => id != null),
    [selectedIds]
  )
  const quoteRequest = useMemo(() => {
    const projectId = Number(currentProjectId)
    const episodeId = Number(currentEpisodeId)
    if (
      action !== 'generate' ||
      !open ||
      !selectedStoryboardIds.length ||
      !Number.isFinite(projectId) ||
      projectId <= 0
    ) {
      return null
    }
    const basePayload = {
      projectId,
      episodeId: Number.isFinite(episodeId) && episodeId >= 0 ? episodeId : 0,
      storyboardIds: selectedStoryboardIds
    }
    if (mode === 'image') {
      const agentCode = String(agent || '').trim()
      const modelCode = String(model || '').trim()
      if (!agentCode || !imageBillingConfig.ready) return null
      return {
        quoteType: 'STORYBOARD_IMAGE_WITH_PROMPT',
        payload: {
          ...basePayload,
          overwrite: withImageCount > 0,
          genAgentCode: agentCode,
          ...(modelCode ? { genModelName: modelCode } : {}),
          ...(imageBillingConfig.aspectRatio
            ? { genAspectRatio: imageBillingConfig.aspectRatio }
            : {}),
          ...(imageBillingConfig.resolution ? { genSize: imageBillingConfig.resolution } : {})
        }
      }
    }
    const modelCode = String(videoModel || '').trim()
    if (!modelCode) return null
    return {
      quoteType: 'STORYBOARD_VIDEO_WITH_PROMPT',
      payload: {
        ...basePayload,
        genModelName: modelCode,
        ...(String(videoAspectRatio || '').trim()
          ? { genAspectRatio: String(videoAspectRatio).trim() }
          : {}),
        ...(formatVideoResolutionForApi(videoQuality)
          ? { genResolution: formatVideoResolutionForApi(videoQuality) }
          : {}),
        genGenerateAudio: videoConfigShowAudio && videoAudio === 'with_audio'
      }
    }
  }, [
    action,
    agent,
    currentEpisodeId,
    currentProjectId,
    imageBillingConfig,
    mode,
    model,
    open,
    selectedStoryboardIds,
    videoAspectRatio,
    videoAudio,
    videoConfigShowAudio,
    videoModel,
    videoQuality,
    withImageCount
  ])
  const generationQuote = useBillingQuote(quoteRequest)

  function toggleSelect(id: string) {
    const item = cardList.find((c) => c.panel.id === id)
    if (!item?.canSelect) return
    const next = new Set(selectedIdsRef.current)
    if (next.has(id)) next.delete(id)
    else next.add(id)
    setSelectedIds(next)
  }

  function onCardClick(item: { panel: StoryboardPanel; canSelect: boolean }) {
    if (item.canSelect) toggleSelect(item.panel.id)
  }

  function toggleSelectAll() {
    const selectable = cardList.filter((c) => c.canSelect).map((c) => c.panel.id)
    if (selectable.every((id) => selectedIdsRef.current.has(id))) {
      const next = new Set(selectedIdsRef.current)
      selectable.forEach((id) => next.delete(id))
      setSelectedIds(next)
    } else {
      const next = new Set(selectedIdsRef.current)
      selectable.forEach((id) => next.add(id))
      setSelectedIds(next)
    }
  }

  function handleCancel() {
    if (confirmLoadingRef.current) return
    onOpenChange(false)
  }

  function resetSelectionOnOpen() {
    if (propsSnapshotRef.current.preselectAll) {
      setSelectedIds(
        new Set(
          computeCardListLive()
            .filter((c) => c.canSelect)
            .map((c) => c.panel.id)
        )
      )
    } else {
      setSelectedIds(new Set())
    }
  }

  async function loadModalListData() {
    setListLoadingBoth(true)
    try {
      const loaded = await refreshStoryboardPanelsFromApiForBatchModal(routeRef.current)
      if (!loaded) {
        message.warning('缺少项目信息，请从「我的作品」打开作品后再操作')
        return
      }
      setRefreshedPanels(loaded)
      setRefreshedVideoPanels(
        useCreationStore.getState().formData.storyboardVideo.panels as StoryboardVideoPanel[]
      )
    } catch (e: unknown) {
      const err = e as { msg?: string; message?: string }
      message.warning(err?.msg || err?.message || '刷新分镜列表失败')
    } finally {
      setListLoadingBoth(false)
    }
  }

  function clearModalListCache() {
    setRefreshedPanels(null)
    setRefreshedVideoPanels(null)
  }

  async function handleModalContentInit() {
    if (!propsSnapshotRef.current.open) return
    const gen = ++modalOpenInitGenRef.current
    await loadModalListData()
    if (gen !== modalOpenInitGenRef.current) return
    resetSelectionOnOpen()
    if (propsSnapshotRef.current.action === 'delete') return
    if (propsSnapshotRef.current.mode === 'image') {
      await loadImageAgents()
      if (gen !== modalOpenInitGenRef.current) return
      await initImageModelSelection()
      return
    }
    if (propsSnapshotRef.current.mode === 'video') {
      await initVideoModelSelection()
    }
  }

  function handleModalAfterOpenChange(nextOpen: boolean) {
    if (!nextOpen) {
      setVideoModelDropdownExpanded(false)
      modalOpenInitGenRef.current++
      invalidateVideoModelLoad()
      clearModalListCache()
    }
  }

  async function handleConfirm() {
    if (listLoadingRef.current || confirmLoadingRef.current) return
    if (selectedIdsRef.current.size === 0) return
    const selectedStoryboardIds = [...selectedIdsRef.current]
      .map((id) => parseServerStoryboardId(id))
      .filter((sid): sid is number => sid != null)
    if (!selectedStoryboardIds.length) {
      message.warning('所选分镜尚未保存到服务器')
      return
    }
    if (action === 'generate' && mode === 'image' && !String(agent || '').trim()) {
      message.warning('请选择智能体')
      return
    }
    if (action === 'generate' && mode === 'video' && !String(videoModel || '').trim()) {
      message.warning('请选择生视频模型')
      return
    }
    const soundEffects: 'none' | 'with-sound' = videoConfigShowAudio
      ? videoAudio === 'with_audio'
        ? 'with-sound'
        : 'none'
      : 'none'
    confirmLoadingRef.current = true
    setConfirmLoading(true)
    try {
      await onConfirm?.({
        action,
        mode,
        selectedStoryboardIds,
        ...(action === 'delete'
          ? {}
          : mode === 'image'
            ? { agent, model }
            : {
                videoModel,
                aspectRatio: String(videoAspectRatio || '').trim() || undefined,
                resolution: String(videoQuality || '').trim().toLowerCase() || undefined,
                soundEffects
              })
      })
      onOpenChange(false)
    } finally {
      confirmLoadingRef.current = false
      setConfirmLoading(false)
    }
  }

  // 原 watch(() => props.open, ..., { immediate: true })
  useEffect(() => {
    if (!open) {
      handleModalAfterOpenChange(false)
      return
    }
    void handleModalContentInit()
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [open])

  // 原 watch(projectCreationMode)
  const creationModeFirstRunRef = useRef(true)
  useEffect(() => {
    if (creationModeFirstRunRef.current) {
      creationModeFirstRunRef.current = false
      return
    }
    if (
      propsSnapshotRef.current.open &&
      propsSnapshotRef.current.action === 'generate' &&
      propsSnapshotRef.current.mode === 'video'
    ) {
      void initVideoModelSelection()
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [projectCreationMode])

  const selectPopupProps = { classNames: { popup: { root: 'bgsm-select-popup' } } }

  const renderCardMedia = (item: CardListItem) => (
    <>
      {item.cover && item.coverKind === 'video' ? (
        <ShimmerVideo
          src={item.cover}
          videoClass="bgsm-card-img"
          objectFit="cover"
          revealDirection="fade"
        />
      ) : item.cover ? (
        <ShimmerImage
          src={item.cover}
          alt={item.label}
          imgClass="bgsm-card-img"
          objectFit="cover"
          revealDirection="fade"
        />
      ) : (
        <div className="bgsm-card-empty">
          <img
            src={emptyImageIconUrl}
            alt=""
            className="empty-image-icon empty-image-icon--xl bgsm-card-empty__icon"
          />
        </div>
      )}
    </>
  )

  const ratioExplanation = videoModel && projectAspectRatio !== videoAspectRatio
    ? `项目比例 ${projectAspectRatio} 不受此模型支持，实际使用 ${videoAspectRatio === 'adaptive' ? '自适应' : videoAspectRatio}。${videoAspectRatio === 'adaptive' ? '输出比例跟随首帧图片或输入视频。' : ''}`
    : videoAspectRatio === 'adaptive' ? '输出比例跟随首帧图片或输入视频。' : ''
  const quoteExplanation = [billingQuoteTextForDisplay(generationQuote.quote), generationQuote.quote?.skuName]
    .filter(Boolean).join(' · ') || generationQuote.error || (generationQuote.loading ? '正在获取预计费用…' : '请选择分镜以预估费用')

  return (
    <Modal
      open={open}
      width={1100}
      footer={null}
      title={null}
      closable={false}
      className="batch-generate-storyboard-modal"
      wrapClassName="create-flow-modal batch-generate-storyboard-wrap"
      forceRender
      onCancel={handleCancel}
      afterOpenChange={handleModalAfterOpenChange}
    >
      <div className="bgsm">
        <header className="bgsm-header">
          <div className="bgsm-title-wrap">
            <h2 className="bgsm-title">{modalTitle}</h2>
            {modalSubtitle ? <p className="bgsm-subtitle">{modalSubtitle}</p> : null}
          </div>
          <button
            type="button"
            className="bgsm-close"
            aria-label="关闭"
            disabled={confirmLoading}
            onClick={handleCancel}
          >
            <CloseOutlined />
          </button>
        </header>

        <div className="bgsm-toolbar">
          <button type="button" className="bgsm-select-all" onClick={toggleSelectAll}>
            <img
              className="bgsm-check-icon"
              src={isAllSelectableChecked ? dialogSelectSelIcon : dialogSelectNorIcon}
              alt=""
            />
            <span className="bgsm-select-all-text">
              全选 ({selectedIds.size}/{selectableCount})
            </span>
          </button>
          {action === 'delete' ? (
            <span className="bgsm-pending bgsm-pending--muted">
              可选择 ({selectableCount}/{effectivePanels.length})
            </span>
          ) : mode === 'video' ? (
            <span className="bgsm-pending">待处理 ({pendingCount})</span>
          ) : (
            <span className="bgsm-pending bgsm-pending--muted">
              已有图片 ({withImageCount}/{effectivePanels.length})
            </span>
          )}
        </div>

        <div className="bgsm-body">
          <div className="bgsm-grid">
            {cardList.map((item) =>
              !item.canSelect ? (
                <Tooltip key={item.panel.id} title={item.disabledTooltip}>
                  <article className="bgsm-card bgsm-card--disabled">
                    <div className="bgsm-card-media">{renderCardMedia(item)}</div>
                    <div className="bgsm-card-meta">
                      <div className="bgsm-card-name">{item.label}</div>
                    </div>
                  </article>
                </Tooltip>
              ) : (
                <article
                  key={item.panel.id}
                  className={
                    selectedIds.has(item.panel.id)
                      ? 'bgsm-card bgsm-card--selected'
                      : 'bgsm-card'
                  }
                  onClick={() => onCardClick(item)}
                >
                  <div className="bgsm-card-media">
                    {renderCardMedia(item)}
                    <img
                      className="bgsm-card-select"
                      src={selectedIds.has(item.panel.id) ? dialogSelectSelIcon : dialogSelectNorIcon}
                      alt=""
                    />
                  </div>
                  <div className="bgsm-card-meta">
                    <div className="bgsm-card-name">{item.label}</div>
                  </div>
                </article>
              )
            )}
          </div>
        </div>

        <footer className="bgsm-footer">
          <div
            className={
              action === 'generate' && mode === 'video'
                ? 'bgsm-footer-left bgsm-footer-left--video'
                : 'bgsm-footer-left'
            }
          >
            {action === 'generate' && mode === 'video' ? (
              <>
                <div className="bgsm-field bgsm-field--video-model">
                  <label className="bgsm-label">生视频模型</label>
                  {videoModelOptions.length ? (
                    <ModelSelectDropdown
                      value={selectedVideoModel}
                      options={videoModelOptions}
                      expanded={videoModelDropdownExpanded}
                      onToggle={() => setVideoModelDropdownExpanded(!videoModelDropdownExpanded)}
                      onClose={() => setVideoModelDropdownExpanded(false)}
                      onSelect={handleSelectVideoModel}
                    />
                  ) : videoModelsLoading ? (
                    <div className="bgsm-video-model-placeholder">加载中…</div>
                  ) : (
                    <div className="bgsm-video-model-placeholder">暂无可用模型</div>
                  )}
                </div>
                <div className="bgsm-field bgsm-field--video-param bgsm-video-ratio">
                  <label className="bgsm-label">画面比例</label>
                  <div className="bgsm-readonly bgsm-ratio-value">
                    <span role="status" aria-live="polite" aria-atomic="true">{videoAspectRatio === 'adaptive' ? '自适应' : videoAspectRatio}</span>
                    {ratioExplanation ? (
                      <Tooltip title={ratioExplanation} trigger={['hover', 'focus', 'click']}>
                        <button type="button" className="bgsm-ratio-info" aria-label={ratioExplanation}>
                          <InfoCircleOutlined aria-hidden="true" />
                        </button>
                      </Tooltip>
                    ) : null}
                  </div>
                </div>
                {videoQualityOptions.length ? (
                  <div className="bgsm-field bgsm-field--video-param">
                    <label className="bgsm-label">清晰度</label>
                    <Select
                      value={videoQuality}
                      onChange={(v) => setVideoQuality(v)}
                      className="bgsm-select"
                      {...selectPopupProps}
                      size="large"
                      options={videoQualityOptions}
                      disabled={!videoQualityOptions.length}
                    />
                  </div>
                ) : null}
                {videoConfigShowAudio && videoAudioOptions.length ? (
                  <div className="bgsm-field bgsm-field--video-param bgsm-field--video-audio">
                    <label className="bgsm-label">音频</label>
                    <Select
                      value={videoAudio}
                      onChange={(v) => setVideoAudio(v)}
                      className="bgsm-select"
                      {...selectPopupProps}
                      size="large"
                      options={videoAudioOptions}
                      disabled={!videoAudioOptions.length}
                    />
                  </div>
                ) : null}
              </>
            ) : null}
          </div>
          <div className="bgsm-actions">
            {action === 'generate' && mode === 'video' ? (
              <Tooltip title={quoteExplanation} trigger={['hover', 'focus', 'click']}>
                <div className="bgsm-fee-value" tabIndex={0} aria-label={`预计费用：${quoteExplanation}`}>
                  <BillingQuoteHint
                    quote={generationQuote.quote}
                    loading={generationQuote.loading}
                    error={generationQuote.error}
                    idleText="选择分镜后显示"
                    active
                  />
                </div>
              </Tooltip>
            ) : (
              <BillingQuoteHint
                quote={generationQuote.quote}
                loading={generationQuote.loading}
                error={generationQuote.error}
                active={Boolean(quoteRequest)}
              />
            )}
            <Button className="bgsm-btn-cancel" disabled={confirmLoading} onClick={handleCancel}>
              <div className="text-gradient">取消</div>
            </Button>
            <Button
              type="primary"
              danger={action === 'delete'}
              loading={confirmLoading}
              className={`bgsm-btn-ok${action === 'delete' ? ' bgsm-btn-ok--danger' : ''}`}
              disabled={selectedIds.size === 0 || listLoading || confirmLoading}
              onClick={handleConfirm}
              icon={
                action === 'generate' && mode === 'video' ? (
                  <img src={starWhiteIconUrl} alt="" />
                ) : undefined
              }
            >
              {action === 'delete' ? '确定' : '批量生成'}
            </Button>
          </div>
        </footer>
      </div>
    </Modal>
  )
}

export default BatchGenerateStoryboardModal
